Require Import Arith.
Require Import List.
Require Import Relations.
Require Import Wellfounded.
Require Import list_util.
Require Import ModEq.
Require Import combi.

Set Implicit Arguments.

Inductive ModOrder (n:nat): relation nat := ModOrder_intro: forall a k, Coprime n a -> MinP (fun x=>x<>0 /\ ModEq n (pow a x) 1) k -> ModOrder n a k.
Hint Constructors ModOrder.

Definition modOrder: forall n a, Coprime n a -> {k|ModOrder n a k}. intros. destruct (nat_eq_dec n 0) as [Hn|Hn]. subst n. assert (a=1). apply GCD_unique with 0 a; auto. destruct (nat_eq_dec a 0); auto. subst a; contradict H; unfold Coprime; auto. subst a. exists 1. apply ModOrder_intro; auto. apply MinP_intro; auto. intros. destruct H0. destruct m; auto.
  destruct (minP) with (P:=fun x=>x<>0/\ModEq n (pow a x) 1) (n:=S(totient n)).  intros. destruct (ModEq_dec n (pow a x) 1); [|right]. destruct (nat_eq_dec x 0); [right|left]; auto. contradict e; destruct e; auto. contradict n0; destruct n0; auto. destruct s as [m H1]. exists m. apply ModOrder_intro; auto. unfold totient in n0. destruct (totient_sig n) as [t Ht]. absurd (t<>0/\ModEq n (pow a t) 1); auto. split. apply Totient_nz with n; auto. apply Euler; auto. Defined.
Theorem ModOrder_nz: forall n a k, ModOrder n a k -> k<>0. Proof. intros. inversion H. inversion H1. destruct H4; auto. Qed.
Theorem ModOrder_unique: forall n a k j, ModOrder n a k -> ModOrder n a j -> k=j. Proof. intros. inversion H. inversion H0. inversion H2. inversion H6. apply le_antisym; auto. Qed.
Theorem ModOrder_Divide: forall n a k d, ModOrder n a k -> Divide k d <-> ModEq n (pow a d) 1. Proof. intros. split; intros. destruct (Divide_multN H0). subst d. rewrite pow_mult. clear H0. inversion H. inversion H1. destruct H4. clear -H7. induction x; simpl; auto. replace 1 with (1*1); auto. inversion H. subst a0 k0. inversion H2. subst n0. destruct H3. destruct (divmod k d) as [[q [r [H6 H7] _]]|];[|contradiction]. subst d. destruct (nat_eq_dec r 0). subst r. rewrite <- plus_n_O. auto. rewrite pow_plus in H0. rewrite pow_mult in H0.
  absurd (k<=r); auto. apply H4. split; auto. clear -H0 H1 H5. induction q. simpl in H0. rewrite <- plus_n_O in H0; auto. apply IHq. simpl in H0. apply ModEq_div with (pow a k). clear -H1. induction k; simpl; auto. rewrite mult_assoc. rewrite mult_1_r. apply ModEq_trans with 1; auto. Qed.
Theorem ModOrder_Totient: forall n a k t, ModOrder n a k -> Totient n t -> Divide k t. Proof. intros. destruct ModOrder_Divide with n a k t; auto. apply H2. apply Euler; auto. inversion H; auto. Qed.
Theorem ModOrder_pow: forall n a k, ModOrder n a k -> forall x y, ModEq n (pow a x) (pow a y) <-> ModEq k x y. Proof. intros n a k H. cut (forall x y, x<=y->ModEq n (pow a x) (pow a y) <-> ModEq k x y). intros. destruct (le_lt_dec x y); auto. split; intros. apply ModEq_sym. apply H0; auto. apply ModEq_sym. apply H0; auto. intros. replace y with (x+(y-x)); [|rewrite <- le_plus_minus]; auto. split; intros. cut (ModEq n (pow a (y-x)) 1). intros. destruct ModOrder_Divide with n a k (y-x); auto. replace x with (x+0) at 1; auto. apply ModEq_plus; auto. apply H4; auto.
  inversion H. revert H1. clear -H2. generalize (y-x). induction x; simpl; intros; auto. apply IHx. apply ModEq_div with a; auto. rewrite pow_plus. replace (pow a x) with (pow a x*1) at 1; [|apply mult_1_r]. apply ModEq_mult; auto. destruct (ModOrder_Divide) with n a k (y-x); auto. apply ModEq_sym. apply H2. apply ModEq_minus with x. rewrite <- plus_n_O; auto. Qed.
Theorem ModOrder_NoDup: forall n a k (Hn:n<>0), ModOrder n a k -> NoDup (map (fun x=>modN Hn (pow a x)) (seq 0 k)). Proof. intros. apply NoDup_map; auto. intros. apply modN_eq__ModEq in H2. destruct ModOrder_pow with n a k x y; auto. apply H3 in H2. destruct (ModEq_multN H2) as [[q H5]|[q H5]]. subst y. destruct q; auto. apply in_seq in H1. destruct H1. contradict H5; auto. simpl. rewrite <- plus_assoc. auto. subst x. destruct q; auto. apply in_seq in H0. destruct H0. contradict H5. simpl. rewrite <- plus_assoc; auto. Qed.
Theorem ModOrder_ModEq: forall n a k b, ModOrder n a k -> ModEq n a b -> ModOrder n b k. Proof. intros. inversion H. subst a0 k0. apply ModOrder_intro. apply GCD_ModEq with a; auto. inversion H2. destruct H3. subst n0. apply MinP_intro; auto. split; auto. apply ModEq_trans with (pow a k); auto. intros. destruct H5. apply H4; split; auto. apply ModEq_trans with (pow b m); auto. Qed.
Theorem ModOrder_PnumN: forall n a k, n<>0->ModOrder n a k-> PnumN (fun x=>exists k, ModEq n (pow a k) x) n k. Proof. intros. assert (Hk:k<>0). eapply ModOrder_nz; eauto. assert (P_dec: forall x, {exists m, ModEq n (pow a m) x}+{~exists m, ModEq n (pow a m) x}).  intros. destruct minP with (n:=k) (P:=fun y=>ModEq n (pow a y) x) as [[m H1]|H1]; [|left|right]. intros. destruct (ModEq_dec n (pow a x0) x); [left|right]; auto. exists m. inversion H1; auto. intros C. destruct C. absurd (ModEq n (pow a  (modN Hk x0)) x ); auto. apply ModEq_trans with (pow a x0); auto. destruct ModOrder_pow with n a k (modN Hk x0) x0; auto. replace k with (length (filter (dec2b P_dec) (seq 0 n))). apply PnumN_filter.
  replace k with (length (map (fun x=>modN H (pow a x)) (seq 0 k))). apply Perm_length. apply NoDup_incl_each_Perm; auto. apply NoDup_map; auto. intros. apply modN_eq__ModEq in H3. apply ModOrder_pow with n a k  x y in H3; auto. replace x with (modN Hk x). replace y with (modN Hk y); auto. apply modN_le_eq. apply in_seq in H2. destruct H2; auto. apply in_seq in H1. destruct H1; auto. intros x Hx. apply filter_In in Hx. destruct Hx. apply dec2b_true in H2.  destruct H2 as [m H3]. apply in_map_iff. exists (modN Hk m). split. replace x with (modN H x). apply ModEq__modN_eq. apply ModEq_trans with (pow a m); auto. destruct ModOrder_pow with n a k (modN Hk m) m; auto. apply modN_le_eq. apply in_seq in H1. destruct H1; auto. apply in_seq. split; auto.
  intros x Hx. apply in_map_iff in Hx. destruct Hx as [y [H1 H2]]. subst x. apply filter_In. split. apply in_seq. split; auto. apply dec2b_true. exists y; auto. rewrite map_length. apply seq_length; auto. Qed.
Hint Resolve ModOrder_unique ModOrder_Divide ModOrder_Totient ModOrder_pow ModOrder_ModEq ModOrder_PnumN.

Inductive ModRoot: relation nat:= ModRoot_intro: forall n g t, Totient n t -> ModOrder n g t -> ModRoot n g.
Hint Constructors ModRoot.

Theorem ModRoot_ModEq: forall n a b, ModRoot n a -> ModEq n a b -> ModRoot n b. Proof. intros. inversion H. apply ModRoot_intro with t; auto. apply ModOrder_ModEq with a; auto. Qed.
Theorem Prime_ModRoot_map: forall p g (Hp:Prime p), ModRoot p g -> Perm (seq 1 (p-1)) (map (fun x=>modN (Prime_nz Hp) (pow g x)) (seq 1 (p-1))). Proof. intros. apply Perm_sym. apply NoDup_incl_Perm. intros y Hy. apply in_map_iff in Hy. destruct Hy as [z [H1 H2]]. subst y. apply in_seq. split. cut (modN (Prime_nz Hp) (pow g z)<>0); intros. destruct (modN (Prime_nz Hp) (pow g z)); auto. intros C. replace 0 with (modN (Prime_nz Hp) 0) in C; auto. apply modN_eq__ModEq in C. inversion H. inversion H1. clear -H5 C Hp. induction z. simpl in C. apply ModEq_le_eq in C; auto. inversion C. simpl in C. apply ModEq_sym in C. apply Euclid_Prime in C; auto. destruct C; auto. absurd (p<=1); auto. inversion H5; auto. rewrite <- le_plus_minus; auto. apply NoDup_map; auto. intros. apply modN_eq__ModEq in H2. cut (forall a b, a<b -> In a (seq 1 (p-1)) -> In b (seq 1 (p-1)) -> ~ModEq p (pow g a) (pow g b)); intros. destruct (le_lt_dec x y). destruct (le_lt_or_eq x y l); auto. contradict H2; auto. apply ModEq_sym in H2; contradict H2; auto. intros C. rewrite <- mult_1_r with (n:=pow g a) in C. rewrite le_plus_minus with a b in C; auto. rewrite pow_plus in C.
  apply ModEq_div in C. inversion H. inversion H7. inversion H11. subst n g0 a0 k n0. assert (t<=b-a). apply H15; split; auto. contradict H3. apply Nat.sub_0_le in H3; auto. replace t with (p-1) in H8. apply in_seq in H4. destruct H4. apply in_seq in H5. destruct H5. contradict H8. apply lt_not_le. apply lt_le_trans with b. destruct b. inversion H5. destruct a. inversion H4. simpl. apply le_n_S. apply le_minus. auto. apply Totient_unique  with p; auto. inversion H. inversion H7. clear -Hp H10. induction a; auto. rewrite map_length; auto. Qed.
Theorem Prime_ModRoot_root: forall p g, Prime p -> ModRoot p g -> forall n, {k|ModEq p (pow g k) n & forall k', ModEq p (pow g k') n -> ModEq (p-1) k k'}+{Divide p n}. intros. destruct (Divide_dec p n) as [Hd|Hd]; [right; auto|left]. destruct findN with (P:=fun x=>x<>0/\ModEq p (pow g x) n) (n:=p) as [[y H1]|H1]. intros. simpl. destruct (nat_eq_dec x 0); [right|]; auto. contradict e. destruct e; auto. destruct (ModEq_dec p (pow g x) n); [left|right]; auto. intros C; destruct C; contradiction. destruct H1. exists y; auto. intros. apply ModOrder_pow with (k:=p-1) (x:=y) (y:=k') (n:=p) (a:=g); auto. inversion H0. replace (p-1) with t; auto. eapply Totient_unique with p; auto. apply ModEq_trans with n; auto. absurd (In (modN (Prime_nz H) n) (seq 1 (p-1))). intros C. apply Perm_In with (m:=map (fun x=>modN (Prime_nz H) (pow g x)) (seq 1 (p-1))) in C. apply in_map_iff in C. destruct C as [x [H2 H3]]. apply in_seq in H3. destruct H3. absurd (x<>0/\ModEq p (pow g x) n). apply H1. rewrite <- le_plus_minus in H4; auto. split. destruct x; auto. inversion H3. apply modN_eq__ModEq in H2; auto. apply Prime_ModRoot_map; auto. apply in_seq. split. destruct (le_lt_dec 1 (modN (Prime_nz H) n)); auto. contradict Hd. inversion l. apply modN_eq__ModEq with (Prime_nz H). rewrite modN_le_eq; auto. inversion H3. rewrite <- le_plus_minus; auto. Defined.
Theorem ModOrder_mult: forall p a b o s, Prime p -> ModOrder p a o -> ModOrder p b s -> Coprime o s -> ModOrder p (a*b) (o*s). Proof. intros. inversion H0. inversion H4. inversion H1. inversion H11. destruct H7. destruct H14. subst a0 k n a1 k0 n0. clear H0 H1 H4 H11. apply ModOrder_intro; auto. apply MinP_intro. split. intros C. apply mult_is_O in C. destruct C; contradiction. replace 1 with (1*1); auto. rewrite pow_mult2. apply ModEq_mult. rewrite mult_comm. rewrite pow_mult. clear -H17. induction s; simpl; auto. replace 1 with (1*1); auto. rewrite pow_mult. clear -H18. induction o; simpl; auto. replace 1 with (1*1); auto. intros. destruct H0.
  cut (Divide o m); intros. cut (Divide s m); intros. destruct (Divide_multN H4) as [q H6]. subst m. rewrite mult_comm in H5. apply Euclid in H5; auto. destruct (Divide_multN H5) as [r H6]. subst q. rewrite mult_comm. rewrite <- mult_assoc. destruct r; simpl; auto. apply Euclid with o; auto. apply ModOrder_Divide with (n:=p) (a:=b) (k:=s) (d:=o*m); auto. apply ModEq_div with (pow a (o*m)); auto. rewrite <- pow_mult2. rewrite mult_1_r. replace (o*m) with (m*o) at 2; auto. repeat rewrite pow_mult. apply ModEq_trans with 1. clear -H1. induction o; simpl; auto. replace 1 with (1*1); auto. clear -H17. induction m; simpl; auto. replace 1 with (1*1); auto. apply Euclid with s; auto. apply ModOrder_Divide with (n:=p) (a:=a) (k:=o) (d:=s*m); auto. apply ModEq_div with (pow b (s*m)); auto. rewrite <- pow_mult2. rewrite mult_1_r. rewrite mult_comm. replace (s*m) with (m*s) at 2; auto. repeat rewrite pow_mult. apply ModEq_trans with 1. clear -H1. induction s; simpl; auto. replace 1 with (1*1); auto. clear -H18. induction m; simpl; auto. replace 1 with (1*1); auto. Qed.
Theorem ModOrder_fold: forall p l, Prime p -> (forall q, In q l->ModOrder p (fst q) (snd q)) -> Forall (Coprime p) (map fst l) -> ForallR Coprime (map snd l) -> ModOrder p (fold_right mult 1 (map fst l)) (fold_right mult 1 (map snd l)). Proof. induction l as [|[a o] l]; simpl; intros; auto. apply ModOrder_intro; auto. apply MinP_intro; auto. intros. destruct H3. destruct m; auto. inversion H1. inversion H2. subst x x0 l0 l1. apply ModOrder_mult; auto. apply (H0 (a,o)); auto. clear -H10. revert H10. generalize (map snd l) as m. induction m; simpl; intros; auto. Qed.
Theorem ModOrder_mult2: forall n m a o s l, Coprime n m -> ModOrder n a o -> ModOrder m a s -> LCM l o s -> ModOrder (n*m) a l. Proof. intros. apply ModOrder_intro. apply Coprime_sym; apply Coprime_mult. inversion H0; auto. inversion H1; auto. apply MinP_intro. split. inversion H2. destruct H3; auto. apply ModEq_Coprime_mult; auto. apply ModOrder_Divide with (d:=l) in H0. apply H0. inversion H2. destruct H3; destruct H6; auto. apply ModOrder_Divide with (d:=l) in H1.  apply H1. inversion H2; destruct H3; destruct H6; auto. intros x Hx. destruct Hx. inversion H2. apply H6. split; auto. split.  rewrite mult_comm in H4. apply ModEq_mult_rev in H4; auto. apply ModOrder_Divide with (d:=x) in H0. apply H0; auto. apply ModOrder_Divide with (d:=x) in H1. apply H1. apply ModEq_mult_rev with n; auto. Qed.
Theorem pow_m1_factorize: forall x n, x<>0 -> pow x n - 1 = (x-1)*(fold_right (fun k b=>pow x k+b) 0 (seq 0 n)). Proof. intros. assert (1<=x). destruct x; auto. induction n. simpl; auto. rewrite seqS. simpl. rewrite fold_right_app. simpl. rewrite <- plus_n_O. replace (fold_right (fun k b=>pow x k+b) (pow x n) (seq 0 n)) with (pow x n+fold_right (fun k b=>pow x k+b) 0 (seq 0 n)). rewrite mult_plus_distr_l. rewrite <- IHn. replace x with (x-1+1) at 1. rewrite mult_plus_distr_r. rewrite mult_1_l. rewrite Nat.add_sub_assoc; auto. rewrite plus_comm. rewrite <- le_plus_minus; auto. generalize (seq 0 n). generalize (pow x n). induction l; simpl; auto. rewrite plus_comm. rewrite <- plus_assoc. f_equal. rewrite plus_comm; auto. Qed.

Inductive PolyCoeff : list nat -> nat -> nat -> Prop:= PolyCoeff_intro: forall l o t, length l=o -> PolyCoeff (t::l) o t.
Hint Constructors PolyCoeff.
Fixpoint polyEval (l:list nat) (n:nat) := match l with nil => 0 |c::l' => c*pow n (length l')+polyEval l' n end.
Definition mod_minus: forall n (nz:n<>0) x, {y|Divide n (x+y) & y<n}. intros. destruct (nat_eq_dec (modN nz x) 0). exists 0; auto. apply Divide_plus; auto. apply modN_eq__ModEq with nz; auto. rewrite e. rewrite modN_le_eq; auto. exists (n-modN nz x). apply ModEq_trans with (modN nz x+(n- modN nz x)); auto. rewrite <- le_plus_minus; auto. replace n with (1*n) at 2; auto. apply multN_Divide. destruct n. absurd (0=0); auto. destruct (modN nz x). absurd (0=0); auto. simpl. apply le_n_S. apply le_minus. Defined.
Definition polyDiv: forall n (nz:n<>0) f o t a b, PolyCoeff f (S o) t -> Divide n (a+b) -> {g|PolyCoeff g o t & forall x, ModEq n (polyEval f x) ((x+a)*polyEval g x+polyEval f b)}. intros n Hn f o. revert f. induction o; intros. exists (t::nil); auto. intros. simpl. rewrite mult_1_r. rewrite <- plus_n_O. inversion H. subst f o t0. destruct l as [|c l]. inversion H1. destruct l. simpl. repeat rewrite mult_1_r. repeat rewrite <- plus_n_O. rewrite plus_assoc. apply ModEq_plus; auto. replace ((x+a)*t) with (t*(x+a)); auto. rewrite <- mult_plus_distr_l. apply ModEq_mult; auto. replace x with (x+0) at 1; auto. rewrite <- plus_assoc; auto. inversion H1.
  destruct f. exfalso; inversion H. destruct f as [|c f]. exfalso; inversion H; inversion H5. assert (n0=t). inversion H; auto. subst n0. destruct (mod_minus Hn (a*t)) as [d H1 H2]; auto. destruct (IHo (c+d::f) (c+d) a b) as [g H3 H4]; auto. inversion H; auto. exists (t::g). inversion H3. apply PolyCoeff_intro; simpl; auto. intros. assert (length f=S o). inversion H. inversion H9; auto. assert (length g=S o). inversion H3. rewrite <- H6; auto. assert (forall x, polyEval (t::c::f) x = t*pow x (o+2)+c*pow x (o+1)+polyEval f x). intros y. simpl. repeat rewrite plus_assoc. f_equal. f_equal. f_equal. rewrite H5; auto. rewrite plus_comm; auto. f_equal. f_equal. rewrite H5; rewrite plus_comm; auto. assert (forall x, polyEval (t::g) x = t*pow x (o+1)+polyEval g x). intros y. simpl. f_equal. f_equal. f_equal. rewrite plus_comm; auto. rewrite H8. rewrite mult_plus_distr_l. rewrite mult_plus_distr_r. rewrite H7. repeat rewrite <- plus_assoc. apply ModEq_plus. apply ModEq_sym. rewrite mult_comm. rewrite <- mult_assoc. apply ModEq_mult; auto. replace (o+2) with (S(o+1)). simpl. rewrite mult_comm; auto. rewrite plus_n_Sm; auto.
  apply ModEq_minus with (d*pow x (o+1)). rewrite plus_assoc. rewrite <- mult_plus_distr_r. rewrite plus_assoc. rewrite mult_assoc. rewrite <- mult_plus_distr_r. replace ((d+c)*pow x (o+1)+polyEval f x) with (0+polyEval (c+d::f) x). apply ModEq_plus. rewrite mult_comm. apply Divide_trans with (d+a*t); auto. rewrite plus_comm; auto. apply ModEq_trans with ((x+a)*polyEval g x+polyEval (c+d::f) b); auto. apply ModEq_plus; auto. simpl. repeat rewrite plus_assoc. apply ModEq_plus; auto. rewrite plus_comm. rewrite mult_plus_distr_r. apply ModEq_plus; auto. rewrite mult_assoc. apply ModEq_mult; auto. rewrite mult_comm. apply ModEq_minus with (a*t). apply ModEq_trans with 0; auto. rewrite <- mult_plus_distr_r. rewrite mult_comm. apply Divide_trans with (a+b); auto. simpl. f_equal. f_equal; auto. f_equal. rewrite plus_comm; auto. Qed.
Theorem polySolutionNum: forall p f o t c, Prime p -> PolyCoeff f o t -> ~Divide p t -> PnumN (fun x=>Divide p (polyEval f x)) p c -> c<=o. Proof. intros p f o t c Hp. revert f t c. assert (Hn:p<>0). contradict Hp; subst p; auto. induction o; intros. inversion H. destruct l. subst o t0 f. simpl in H1. replace c with 0; auto. eapply PnumN_unique; [|eapply H1]. rewrite mult_1_r. rewrite <- plus_n_O. auto. inversion H2. destruct (nat_eq_dec c 0) as [Hc|Hc]. subst c; auto. destruct (PnumN_ex H1). destruct (H2 Hc) as [d [H4 H5]]. destruct (mod_minus Hn d) as [e H6 H7]. destruct (polyDiv Hn e d H) as [g H8 H9]; auto. rewrite plus_comm; auto. apply PnumN_equiv with (Q:=fun x=>Divide p (x+e) \/ Divide p (polyEval g x)) in H1. assert (PnumN (fun x=>Divide p (x+e)) p 1). apply PnumN_one with d; auto. intros. rewrite <- modN_le_eq with p Hn y; auto. rewrite <- modN_le_eq with p Hn d; auto. apply ModEq__modN_eq. apply ModEq_minus with e; auto. rewrite plus_comm. apply ModEq_trans with 0; auto. rewrite plus_comm; auto. destruct (pnumN) with (P:=fun x=>Divide p (polyEval g x)) (n:=p) as [c' H11]. intros; apply Divide_dec. assert (c<=1+c'). eapply PnumN_or. eapply H10. eapply H11. auto. apply le_trans with (1+c'); auto. simpl. apply le_n_S. apply IHo with g t; auto. intros. split; intros. apply Euclid_Prime; auto. apply Divide_minus with (polyEval f d); auto. rewrite plus_comm. apply ModEq_trans with (polyEval f x); auto. apply ModEq_trans with ((x+e)*polyEval g x+polyEval f d); auto. apply Divide_plus; auto. destruct H11. rewrite mult_comm; apply Divide_trans with (x+e); auto. apply Divide_trans with (polyEval g x); auto. Qed.
Lemma repeat0_head: forall f x n, polyEval (repeat 0 n++f) x = polyEval f x. Proof. induction n; simpl; auto. Qed.
Lemma fold_app_length: forall {X:Type} l ll, length (fold_right (app (A:=X)) l ll) = fold_right plus (length l) (map (length (A:=X)) ll). Proof. induction ll; simpl; auto. rewrite app_length; f_equal; auto. Qed.
Theorem polyRootNum: forall p d, Prime p -> Divide d (p-1) -> PnumN (fun x=>ModEq p (pow x d) 1) p d. Proof. intros. assert (Hp:p-1<>0). contradict H. destruct p; auto. destruct p; auto. inversion H. destruct (Divide_multN H0) as [e H1]. assert (Hd:d<>0). contradict Hp. subst d. rewrite H1; auto. assert (He:e<>0). contradict Hp. subst e. rewrite H1; auto. assert (PnumN (fun x=>ModEq p (pow x (e*d)) 1) p (e*d)). rewrite <- H1. cut (forall x, 1<=x->x<=p->PnumN (fun x=>ModEq p (pow x (p-1)) 1) x (x-1)). intros. apply H2; auto. intros x Hx. induction Hx; intros. simpl. apply PnumN_NP; auto. rewrite pow0n; auto. intros C. apply Divide_le in C; auto. contradict C; auto. rewrite <- minus_Sn_m; auto. apply PnumN_P; auto. apply Fermat; auto. contradict H2. apply Divide_le in H2; auto. contradict Hx; subst m; auto. destruct (pnumN) with (P:=fun x=>ModEq p (pow x d) 1) (n:=p) as [c H3]. intros. apply ModEq_dec. replace d with c at 1; auto. apply le_antisym.
  assert (H4:PolyCoeff (1::repeat 0 (d-1)++p-1::nil) d 1). apply PolyCoeff_intro. rewrite app_length. rewrite repeat_length. simpl. rewrite plus_comm. rewrite <- le_plus_minus; auto. apply (polySolutionNum H H4). intros C. apply Divide_le in C; auto. contradict C; auto. eapply PnumN_equiv; [|eapply H3]. simpl; intros. rewrite app_length. rewrite repeat_length. rewrite <- plus_assoc. simpl. replace (d-1+1) with d. rewrite repeat0_head. simpl. rewrite mult_1_r. rewrite <- plus_n_O. split; intros. apply ModEq_trans with (1+(p-1)); auto. rewrite <- le_plus_minus; auto. apply Divide_refl. apply ModEq_minus with (p-1). rewrite plus_comm. apply ModEq_trans with 0; auto. rewrite plus_comm. rewrite <- le_plus_minus; auto. apply Divide_refl. rewrite plus_comm. apply le_plus_minus; auto.
  rewrite <- mult_1_l at 1. apply plus_le_reg_l with ((e-1)*d). rewrite <- mult_plus_distr_r. rewrite plus_comm. rewrite <- le_plus_minus; auto. destruct pnumN with (P:=fun x=>Divide p (polyEval (fold_right (app (A:=nat)) (1::nil) (repeat (1::repeat 0 (d-1)) (e-1))) x)) (n:=p) as [f H4]. intros. apply Divide_dec. assert (f<=(e-1)*d). assert (PolyCoeff (fold_right (app (A:=nat)) (1::nil) (repeat (1::repeat 0 (d-1)) (e-1))) ((e-1)*d) 1). generalize (e-1). induction n; simpl; auto. apply PolyCoeff_intro; auto. rewrite app_length. rewrite repeat_length. inversion IHn. rewrite <- H6. simpl. rewrite <- plus_n_Sm. rewrite <- plus_Sn_m. f_equal. destruct d. contradict Hd; auto. simpl. rewrite <- minus_n_O; auto. apply (polySolutionNum H H5); auto. intros C. apply Divide_le in C; auto. contradict C; auto. apply le_trans with (f+c); [|apply plus_le_compat_r]; auto. eapply PnumN_or. eapply H4. eapply H3. simpl. eapply PnumN_equiv; [|eapply H2]. intros; simpl. clear H2 H3 H4 H5 c f. assert (polyEval (fold_right (app (A:=nat)) (1::nil) (repeat (1::repeat 0 (d-1)) (e-1))) x = polyEval (fold_right (app (A:=nat)) (0::nil) (repeat (1::repeat 0 (d-1)) (e-1))) x+1). generalize (e-1). induction n; simpl; auto. repeat rewrite <- plus_assoc. f_equal. f_equal. repeat rewrite app_length. f_equal. repeat rewrite fold_app_length; auto. simpl. repeat rewrite repeat0_head; auto. assert (polyEval (fold_right (app (A:=nat)) (1::nil) (repeat (1::repeat 0 (d-1)) (e-1))) x * pow x d = polyEval (fold_right (app (A:=nat)) (0::nil) (repeat (1::repeat 0 (d-1)) (e-1))) x + pow x (e*d)). replace (e*d) with (S(e-1)*d).
  generalize (e-1). induction n; simpl; repeat rewrite <- plus_n_O; auto. rewrite mult_plus_distr_r. repeat rewrite repeat0_head; repeat rewrite app_length; repeat rewrite repeat_length; repeat rewrite fold_app_length. rewrite <- pow_plus. rewrite plus_comm. f_equal. rewrite IHn. rewrite plus_comm. f_equal. f_equal. simpl. rewrite map_repeat. simpl. rewrite repeat_length. rewrite minus_Sn_m; auto. simpl. rewrite <- minus_n_O. clear -Hd. induction n; simpl; auto. rewrite <- plus_n_O. rewrite plus_comm. apply le_plus_minus; auto. rewrite IHn. repeat rewrite plus_assoc. f_equal; auto. f_equal. rewrite map_repeat. simpl. rewrite repeat_length. rewrite minus_Sn_m; auto. simpl. rewrite <- minus_n_O. rewrite plus_comm. f_equal. clear -Hd. induction n; simpl. rewrite plus_comm. rewrite <- le_plus_minus; auto. rewrite <- IHn. repeat rewrite plus_assoc. f_equal; auto. f_equal. rewrite minus_Sn_m; auto. simpl. rewrite <- minus_n_O; auto. split; intros. destruct (Prime_Coprime_Divide (polyEval (fold_right (app (A:=nat)) (1::nil) (repeat (1::repeat 0 (d-1)) (e-1))) x)  H); auto; right. eapply ModEq_div. eapply H5. rewrite H3. rewrite mult_1_r. rewrite H2; auto. apply ModEq_minus with (polyEval (fold_right (app (A:=nat)) (0::nil) (repeat (1::repeat 0 (d-1)) (e-1))) x). rewrite <- H3. rewrite <- H2. destruct H4. apply ModEq_trans with 0; auto. rewrite mult_comm. apply ModEq_sym. eapply Divide_trans. eapply H4. auto. rewrite <- mult_1_r. auto. Qed.

Theorem Prime_ModRoot: forall p, Prime p -> exists a, ModRoot p a. Proof. intros. assert (2<=p). auto. assert (Hp:p-1<>0). contradict H0. apply le_not_lt. destruct p; auto. destruct p; auto. inversion H0. apply le_lt_or_eq in H0. destruct H0; [|subst p; exists 1]. destruct (fundamental2 (p-1)) as [[pl [H1 [H2 [H3 H4]]]]|H1]; [|contradiction]. cut (exists l, map snd l = map (fun p=>pow (fst p) (snd p)) pl /\forall q, In q l->ModOrder p (fst q) (snd q)). intros. destruct H5 as [l [H5 H6]]. exists (fold_right mult 1 (map fst l)). apply ModRoot_intro with (p-1); auto. replace (p-1) with (fold_right mult 1 (map snd l)). apply ModOrder_fold; auto. apply Forall_forall. intros q Hq. apply in_map_iff in Hq. destruct Hq as [[r s] [H7 H8]]. simpl in H7. subst r. apply H6 in H8. simpl in H8. inversion H8; auto. rewrite H5. clear -H2 H3 H4. induction pl as [|[p c] pl]; simpl; auto. inversion H2. inversion H3. inversion H4. subst x x0 x1 l l0 l1. apply ForallR_cons; auto. intros y Hy.  apply in_map_iff in Hy. destruct Hy as [[q d] [H10 H11]]. subst y. simpl. destruct (Prime_pow_Coprime_Divide (pow q d) c H1); auto. absurd (In p (map fst pl)); auto. replace p with q. apply in_map_iff. exists (q,d); auto. symmetry. apply repeat_spec with d. apply Prime_mult_In; auto. cut (Prime q). intros. clear -H0. induction d; simpl; auto. apply Forall_forall with (P:=Prime) (l:=map fst pl); auto. apply in_map_iff. exists (q,d); auto. replace (fold_right mult 1 (repeat q d)) with (pow q d); auto. clear -d. induction d; simpl; auto. rewrite H1. rewrite H5. clear -pl. induction pl; simpl; auto.
  cut (forall q, In q pl -> exists a, ModOrder p a (pow (fst q) (snd q))). intros. clear -H5. induction pl. exists nil; simpl; auto. split; auto. intros. destruct H. destruct (H5 a) as [o H6]; auto. destruct IHpl as [l [H7 H8]]. intros. apply H5; auto. exists ((o, pow (fst a) (snd a))::l). simpl. split. f_equal; auto. intros. destruct H; auto. subst q. simpl. auto. 
  intros. destruct q as [q c]. simpl. assert (c<>0). apply Forall_forall with (l:=map snd pl) (P:=fun x=>x<>0); auto. apply in_map_iff. exists (q,c); auto. assert (Prime q). apply Forall_forall with (l:=map fst pl) (P:=Prime); auto. apply in_map_iff. exists (q,c); auto. assert (Divide (pow q c) (p-1)). rewrite H1. clear -H5. induction pl. destruct H5. destruct H5. simpl. subst a. simpl; rewrite mult_comm; auto. simpl. eapply Divide_trans. eapply IHpl; auto. auto. assert (Divide (pow q (c-1)) (p-1)). apply Divide_trans with (pow q c); auto. apply pow_Prime_Divide; auto. exists (c-1); split; auto. apply le_minus. assert (PnumN (fun x=>ModEq p (pow x (pow q c)) 1) p (pow q c)). apply polyRootNum; auto. assert (PnumN (fun x=>ModEq p (pow x (pow q (c-1))) 1) p (pow q (c-1))). apply polyRootNum; auto. destruct (PnumN_lt) with (P:=fun x=>ModEq p (pow x (pow q (c-1))) 1) (Q:=fun x=>ModEq p (pow x (pow q c)) 1) (n:=p) (a:=pow q (c-1)) (b:=pow q c) as [x [Ha [Hb Hc]]]; auto. destruct c. contradict H6; auto. simpl. rewrite <- minus_n_O. remember (pow q c) as a. destruct a. symmetry in Heqa. contradict Heqa. apply pow_nz. contradict H7; subst q; auto. destruct q. contradict H7; auto. destruct q. contradict H7; auto. simpl. rewrite <- plus_n_Sm. auto.
  exists x. assert (Coprime p x). destruct (Prime_Coprime_Divide  x H); auto. contradict Ha. apply Divide_le in H12; auto. intros C; subst x. replace (pow 0 (pow q c)) with 0 in Hc. absurd (0=1); auto. apply ModEq_le_eq with p; auto. rewrite pow0n; auto. destruct (modOrder H12) as [k H13]. destruct (ModOrder_Divide (pow q c) H13). destruct (ModOrder_Divide (pow q (c-1)) H13). apply H15 in Hc. apply pow_Prime_Divide in Hc; auto. destruct Hc as [m [H18 H19]]. subst k. apply le_lt_or_eq in H19. destruct H19; [|subst m]; auto. contradict Hb. apply H16. apply pow_Prime_Divide; auto. exists m; split; auto. destruct c. contradict H6; auto. simpl. rewrite <- minus_n_O; auto. apply ModRoot_intro with (2-1); auto. simpl. apply ModOrder_intro; auto. apply MinP_intro; auto. intros. destruct m; auto. destruct H0. contradict H0; auto. Qed.
Definition modRoot: forall p, Prime p -> {a|ModRoot p a}. intros. destruct minP with (P:=fun x=>Coprime p x/\ModOrder p x (p-1)) (n:=p) as [[a H1]|H1]. intros. destruct (Coprime_dec p x); [|right]. destruct (modOrder c) as [k H1]. destruct (nat_eq_dec k (p-1)); [subst k;left|right]; auto. contradict n. destruct n. apply ModOrder_unique with p x; auto. contradict n; destruct n; auto. exists a. inversion H1. destruct H0. apply ModRoot_intro with (p-1); auto. exfalso. destruct (Prime_ModRoot H) as [a Ha]. assert (Hp:p<>0). contradict H; subst p; auto. absurd (Coprime p (modN Hp a)/\ModOrder p (modN Hp a) (p-1)); auto. apply ModRoot_ModEq with (b:=modN Hp a) in Ha; auto. inversion Ha. inversion H2. split; auto. replace (p-1) with t; auto. apply Totient_unique with p; auto. Defined.

Theorem Prime_pow_ModRoot: forall p e, Prime p -> 3<=p -> exists a, ModRoot (pow p e) a. Proof. intros.
  (* use a or a+p which a is root of p *)
  assert (exists a k, pow a (p-1) = k*p+1 /\ ~Divide p k /\ ModOrder p a (p-1)). destruct (Prime_ModRoot H) as [a H1]. inversion H1. subst n g. assert (t=p-1). apply Totient_unique with p; auto. subst t. inversion H3. subst a0 k. inversion H5. subst n. destruct H6. destruct (ModEq_multN_lt H8) as [q H9]; auto. destruct (Divide_dec p q) as [H10|H10]; [|exists a; exists q; auto]. exists (a+p). exists (q+pow a (p-2)*(p-1)+fold_right plus 0 (map (fun k=>combi (p-1)k*pow a (p-1-k)*pow p (k-1)) (seq 2 (p-2)))). split; [|split]. rewrite poly_combi. replace (seq 0 (S (p-1))) with (0::1::seq 2 (p-2)). simpl. symmetry. rewrite plus_comm. rewrite <- plus_assoc. rewrite mult_plus_distr_r. rewrite plus_assoc. f_equal. rewrite Combi_0. rewrite <- minus_n_O. rewrite H9. rewrite mult_1_l. rewrite mult_1_r; auto. rewrite mult_plus_distr_r. f_equal. rewrite Combi_1. f_equal. rewrite mult_comm. f_equal. f_equal. destruct p. inversion H0. simpl. rewrite <- minus_n_O; auto. rewrite mult_1_r; auto. rewrite mult_comm. rewrite mult_fold_plus. rewrite mult_0_r. f_equal. rewrite map_map. apply map_ext_in. intros x Hx. rewrite mult_comm. repeat rewrite <- mult_assoc. f_equal. f_equal. apply in_seq in Hx. destruct Hx. destruct x. inversion H11. simpl. rewrite <- minus_n_O; auto. destruct p. inversion H0. destruct p. contradict H0; auto. simpl. rewrite <- minus_n_O; auto. cut (~Divide p (pow a (p-2)*(p-1))). intros C. contradict C. rewrite plus_comm in C. apply Divide_minus in C. apply Divide_minus in C; auto. generalize (p-2). induction n; auto. rewrite seqS. rewrite map_app. rewrite fold_plus_app. apply Divide_plus; auto. simpl. rewrite <- plus_n_O. apply Divide_trans with (p*pow p n); auto. rewrite mult_comm; auto. intros C. apply Euclid_Prime in C; auto. destruct C. absurd (Divide p a). intros C. inversion H4. absurd (p<=1); auto. revert H11. generalize (p-2). induction n; simpl; intros. apply Divide_le in H11; auto. contradict H11; auto. apply Euclid_Prime in H11; auto. destruct H11; auto. apply Divide_le in H11. contradict H11. apply lt_not_le. destruct p. inversion H0. simpl. rewrite <- minus_n_O; auto. destruct p. inversion H0. destruct p. contradict H0; auto. auto. apply ModOrder_ModEq with a; auto. replace a with (a+0) at 1; auto. apply ModEq_plus; auto. apply Divide_refl. 
  (* e=0 *)
  destruct (nat_eq_dec e 0) as [He|He]. subst e. simpl. exists 1. apply ModRoot_intro with 1; auto. apply ModOrder_intro; auto. apply MinP_intro; auto. intros. destruct H2. destruct m; auto.
  (* e<>0 *)
  assert (Hpnz:p-1<>0). destruct p. inversion H0. destruct p. contradict H0; auto. simpl; auto. destruct H1 as [a [k [H2 [H3 H4]]]]. exists a. apply ModRoot_intro with ((p-1)*pow p (e-1)). apply Prime_pow_Totient; auto. assert (Ho: Coprime (pow p e) a). destruct (Prime_pow_Coprime_Divide a e H); auto. absurd (Divide p (pow a (p-1))). rewrite H2. intros C. apply Divide_minus in C; auto. apply Divide_le in C; auto. contradict C; auto. apply ModEq_trans with (pow 0 (p-1)); auto. rewrite pow0n; auto.
    (* let o is order *) destruct (modOrder Ho) as [o H5]. assert (Divide o ((p-1)*pow p (e-1))). apply ModOrder_Divide with (d:=(p-1)*pow p (e-1)) in H5. apply H5; auto. replace ((p-1)*pow p (e-1)) with o; auto. apply Divide_antisym; auto. destruct (powDivide o (Prime_le H)) as [[q [r H7 H8]]|H7]; [|apply ModOrder_nz in H5; contradiction]. rewrite mult_comm in H7; subst o. assert (r<=p-1). apply Divide_le; auto. apply Euclid with (pow p (e-1)). apply Coprime_pow. destruct (Prime_Coprime_Divide r H); auto; contradiction. rewrite mult_comm; apply Divide_trans with (r*pow p q); auto. rewrite mult_comm; auto. apply le_lt_or_eq in H6. destruct H6. contradict H6. apply le_not_lt. inversion H4. subst a0 k0. inversion H7. subst n. apply H10. split. contradict H8; subst r; auto. apply ModEq_trans with (pow (pow a (pow p q)) r). apply ModEq_pow. clear -H H6. induction q. simpl. rewrite mult_1_r; auto. rewrite powS. rewrite pow_mult. apply ModEq_trans with (pow a p); auto. replace p with (S(p-1)) at 2. rewrite powS. replace a with (a*1) at 1. apply ModEq_mult; auto. rewrite mult_1_r; auto. rewrite minus_Sn_m; auto. simpl. rewrite <- minus_n_O; auto. rewrite <- pow_mult. apply ModEq_mult_rev with (pow p (e-1)). replace (pow p (e-1)*p) with (pow p e). inversion H5. inversion H12. destruct H15; auto. rewrite mult_comm. rewrite <- powS. f_equal. destruct e. contradict He; auto. simpl. rewrite <- minus_n_O; auto. subst r.
    destruct (le_lt_dec (e-1) q) as [H9|H9]. apply Divide_mult. apply pow_Prime_Divide; auto. exists (e-1); auto. clear He. assert (He:2<=e). destruct e. inversion H9. destruct e; auto. inversion H9. absurd (ModEq (pow p e) (pow a ((p-1)*pow p (e-2))) 1). clear -H H0 H2 H3 Hpnz He. cut (exists j, pow a ((p-1)*pow p (e-2)) = j*pow p (e-1) + 1 /\ ~Divide p j). intros. destruct H1 as [j [H4 H5]]. rewrite H4. rewrite plus_comm. replace 1 with (1+0) at 3; auto.  intros C.  apply ModEq_minus in C. rewrite mult_comm in C. replace (pow p e) with (pow p (e-1)*p) in C. apply ModEq_sym in C. apply Divide_div in C; auto. rewrite mult_comm; auto. rewrite <- powS. f_equal. rewrite minus_Sn_m; auto. simpl. rewrite <- minus_n_O; auto. induction He. exists k. simpl. repeat rewrite mult_1_r; auto. destruct IHHe as [j [H4 H5]]. repeat rewrite <- minus_Sn_m; auto. rewrite powS. rewrite mult_comm. rewrite <- mult_assoc. rewrite pow_mult. rewrite mult_comm in H4. rewrite H4. rewrite plus_comm. rewrite poly_combi. exists (j+ fold_right plus 0 (map (fun k=>combi p k* pow j k*pow p (k*(m-1)-m)) (seq 2 (p-1)))). split. replace (seq 0 (S p)) with (0::1::seq 2 (p-1)). simpl. symmetry. rewrite plus_comm. f_equal. rewrite Combi_0. rewrite pow_1n. auto. rewrite mult_plus_distr_r. f_equal. rewrite Combi_1. rewrite pow_1n. repeat rewrite mult_1_r. repeat rewrite mult_assoc. f_equal; auto. rewrite mult_comm. rewrite mult_fold_plus. rewrite mult_0_r. f_equal. rewrite map_map. apply map_ext_in. intros x Hx. rewrite pow_1n. rewrite mult_1_r. rewrite mult_comm. repeat rewrite <- mult_assoc. f_equal. rewrite pow_mult2. f_equal. rewrite <- powS. rewrite <- pow_plus. rewrite <- pow_mult. f_equal. rewrite minus_Sn_m; auto. simpl. rewrite <- minus_n_O. rewrite plus_comm. rewrite <- le_plus_minus; auto. apply in_seq in Hx. destruct Hx. destruct x. inversion H1. destruct x. contradict H1; auto. destruct m. inversion He. destruct m. contradict He; auto. simpl. apply le_n_S. rewrite <- plus_n_Sm; auto. simpl. f_equal. replace p with (S (p-1)) at 2; auto. destruct p. contradict Hpnz; auto. simpl. rewrite <- minus_n_O; auto.
    rewrite plus_comm. contradict H5. apply Divide_minus in H5; auto. cut (2<=p-1). generalize (p-1). intros. induction H1. simpl. apply Divide_plus. apply Divide_trans with (combi p 2). apply Combi_Prime; auto. rewrite <- mult_assoc; rewrite mult_comm; auto. repeat rewrite <- plus_n_O. destruct m. inversion He. simpl. destruct m. contradict He; auto. simpl. apply Divide_trans with (pow p (m+S(m+S m)-S m)); auto. rewrite <- plus_n_Sm. simpl. rewrite minus_plus. rewrite plus_comm. simpl. rewrite mult_comm; auto. rewrite seqS. rewrite map_app. rewrite fold_plus_app. apply Divide_plus; auto. simpl. destruct m. inversion He. simpl. repeat rewrite <- minus_n_O. rewrite <- plus_n_O. destruct m. contradict He; auto. simpl. rewrite <- plus_n_Sm. simpl. rewrite minus_plus. apply Divide_trans with (pow p (m+m0*S m)); auto. destruct m0. inversion H1. simpl. rewrite <- plus_n_Sm. rewrite powS. rewrite mult_comm; auto. destruct p. inversion H0. simpl. rewrite <- minus_n_O; auto. 
    apply ModOrder_Divide with (d:=(p-1)*pow p (e-2)) in H5. apply H5. apply Divide_mult. apply pow_Prime_Divide; auto. exists q. split; auto. replace (e-1) with (S(e-2)) in H9; auto. rewrite minus_Sn_m; auto. Qed.

(* Carmichael function *)
Inductive Carmichael: relation nat:= Carmichael_intro: forall n c a, (forall b, Coprime n b-> ModEq n (pow b c) 1) -> ModOrder n a c -> Carmichael n c.
Hint Constructors Carmichael.

Theorem Carmichael_nz: forall n c, Carmichael n c -> c<>0. Proof. intros. inversion H. inversion H1. inversion H5. destruct H8; auto. Qed.
Theorem Carmichael_Min: forall n c, Carmichael n c -> MinP (fun x=>x<>0 /\ forall a, Coprime n a->ModEq n (pow a x) 1) c. Proof. intros. inversion H. subst n0 c0. inversion H1. subst a0 k. inversion H3. subst n0. destruct H4. apply MinP_intro; auto. intros. destruct H7; auto. Qed.
Theorem Carmichael_unique: forall n a b, Carmichael n a -> Carmichael n b -> a=b. Proof. intros. destruct (Carmichael_Min H). destruct (Carmichael_Min H0). apply le_antisym; auto. Qed.
Theorem Carmichael_0: Carmichael 0 1. Proof. intros. apply Carmichael_intro with 1. intros. replace b with 1; auto. apply GCD_unique with 0 b; auto. apply GCD_0n. contradict H; subst b; apply GCD_00. apply ModOrder_intro; auto. apply MinP_intro; auto. intros. destruct H. destruct m; auto. Qed.
Theorem Carmichael_1: Carmichael 1 1. Proof. intros. apply Carmichael_intro with 1. intros. auto. apply ModOrder_intro; auto. apply MinP_intro; auto. intros. destruct H. destruct m; auto. Qed.
Theorem Carmichael_2: Carmichael 2 1. Proof. intros. apply Carmichael_intro with 1. intros. rewrite pow1. destruct (divmod 2 b) as [[q [r [H1 H2] _]]|H1]; auto. subst b. inversion H2; auto. inversion H1. subst r. absurd (2<=1); auto. inversion H. apply H4; auto. inversion H4. inversion H1. apply ModOrder_intro; auto. apply MinP_intro; auto. intros. destruct H. destruct m; auto. Qed.
Theorem Carmichael_4: Carmichael 4 2. Proof. intros. apply Carmichael_intro with 3. intros. destruct (divmod 2 b) as [[q [r [H1 H2] _]]|H1]. subst b. inversion H2. simpl. rewrite mult_1_r. rewrite mult_plus_distr_r. rewrite mult_1_l. rewrite mult_plus_distr_l. rewrite mult_1_r. replace 1 with (0+1) at 7; auto. repeat rewrite plus_assoc. apply ModEq_plus; auto. apply ModEq_sym. rewrite <- plus_assoc. apply Divide_plus. replace (q*2*(q*2)) with (q*q*4); auto. repeat rewrite <- mult_assoc. f_equal. symmetry. rewrite mult_comm. rewrite <- mult_assoc; auto. rewrite <- mult_plus_distr_l. auto. inversion H1. subst r. absurd (2<=1); auto. inversion H. apply H4. split; auto. replace 4 with (2*2); auto. inversion H4. inversion H1. apply ModOrder_intro. apply Coprime_sym. destruct Prime_Coprime_Divide with 3 4. apply Prime_build; auto. intros. assert (x<=3); auto. inversion H0; auto. inversion H2. subst x. absurd (2<=1); auto. apply Divide_le; auto. apply Divide_minus with 2; auto. inversion H4; auto. inversion H6. subst x. absurd (3=0); auto. auto. absurd (3<=1); auto. apply Divide_le; auto. apply Divide_minus with 3; auto. apply MinP_intro. split; auto. simpl. replace 9 with (2*4+1); auto. intros. destruct H. destruct m. contradict H; auto. destruct m; auto. simpl in H0. absurd (3=1); auto. assert (4<>0). auto. apply ModEq__modN_eq with (nz:=H1) in H0; auto. Qed.
Theorem Carmichael_pow2: forall e, 3<=e -> Carmichael (pow 2 e) (pow 2 (e-2)). Proof. intros. assert (Ht: forall b, Coprime (pow 2 e) b -> ModEq (pow 2 e) (pow b (pow 2 (e-2))) 1). intros b H0. destruct (divmod 2 b) as [[q [r [H1 H2] _]]|H1]; [|inversion H1]. inversion H2. subst r b. clear H2 H0. induction H. simpl. rewrite mult_1_r. rewrite mult_plus_distr_r. rewrite mult_1_l. replace 1 with (0+1) at 7; auto. rewrite plus_assoc. apply ModEq_plus; auto. rewrite mult_plus_distr_l. rewrite mult_1_r. rewrite <- plus_assoc. rewrite <- mult_plus_distr_l. simpl. replace (q*4) with (1*(q*4)); auto. replace (q*2*(q*2)) with (q*(q*4)). rewrite <- mult_plus_distr_r. rewrite mult_assoc. apply ModEq_sym. rewrite mult_comm. replace 8 with (4*2); auto. apply Divide_mult. destruct (divmod 2 q) as [[s [r [H1 H2] _]]|H1]; [|inversion H1]. inversion H2. subst r q. apply Divide_trans with (s*2+1+1); auto. rewrite <- plus_assoc; auto. remember (s*2+1+1) as u. rewrite mult_comm; auto. inversion H0. subst r q. apply Divide_trans with (s*2+0); auto. inversion H4. rewrite <- mult_assoc. f_equal. symmetry. rewrite mult_comm. rewrite <- mult_assoc. f_equal. destruct (ModEq_multN_lt IHle) as [a H0]. destruct m; auto. inversion H. replace (pow 2 (S m-2)) with (2*pow 2 (m-2)). rewrite pow_mult. rewrite H0. rewrite powS. rewrite powS. rewrite pow1. rewrite mult_plus_distr_r. rewrite mult_1_l. rewrite plus_assoc. replace 1 with (0+1) at 8; auto. apply ModEq_plus; auto. rewrite mult_plus_distr_l. rewrite mult_1_r. rewrite <- plus_assoc. apply ModEq_sym. apply Divide_plus. apply Divide_trans with (pow 2 m*pow 2 m). rewrite <- pow_plus. rewrite <- powS. destruct m. inversion H. replace (S m+S m) with ((S (S m))+m). rewrite pow_plus. rewrite mult_comm; auto. simpl. f_equal. rewrite plus_n_Sm; auto. apply Divide_trans with (a*(pow 2 m*pow 2 m)); auto. rewrite <- mult_assoc. apply Divide_mult. apply Divide_mult; auto. rewrite <- mult_plus_distr_r. replace (a+a) with (2*a); auto. rewrite <- mult_assoc. apply Divide_mult; auto. simpl. f_equal; auto. rewrite <- minus_Sn_m; auto. inversion H4. subst m r b. absurd (2<=1); auto. inversion H0. apply H3; split; auto. destruct e. inversion H. rewrite powS; rewrite mult_comm; auto. inversion H6.
  apply Carmichael_intro with 3; auto. assert (Hc:Coprime (pow 2 e) 3). destruct Prime_pow_Coprime_Divide with 2 3 e; auto. absurd (2<=1); auto. apply Divide_le; auto. apply Divide_minus with 2; auto. assert (Hd:~ModEq (pow 2 e) (pow 3 (pow 2 (e-3))) 1). apply le_lt_or_eq in H. destruct H. assert (exists k, pow 3 (pow 2 (e-3)) = k*pow 2 (e-1)+1 /\ ~Divide 2 k). clear Ht Hc. induction H. simpl. exists 1. split; auto. intros C. absurd (2<=1); auto. replace (S m-3) with (S(m-3)). rewrite powS. rewrite pow_mult. destruct IHle as [k [H0 H1]]. rewrite H0. rewrite powS. rewrite pow1. rewrite mult_plus_distr_l. rewrite mult_1_r. rewrite mult_plus_distr_r. rewrite mult_1_l. exists (k*k*pow 2 (m-2)+k). split. rewrite plus_assoc. f_equal. rewrite mult_plus_distr_r. rewrite <- plus_assoc. f_equal. repeat rewrite <- mult_assoc. f_equal. rewrite mult_comm. repeat rewrite <- mult_assoc. f_equal. repeat rewrite <- pow_plus. f_equal. destruct m. inversion H. simpl. destruct m. contradict H; auto. simpl. rewrite <- minus_n_O. rewrite plus_n_Sm; auto. rewrite <- minus_Sn_m; auto. rewrite powS. rewrite mult_assoc. rewrite <- mult_plus_distr_r. f_equal. rewrite mult_comm; simpl; auto. apply le_trans with 4; auto. contradict H1. apply Divide_minus in H1; auto. apply Divide_trans with (pow 2 (m-2)); auto. destruct m. inversion H. rewrite <- minus_Sn_m; auto. rewrite powS; rewrite mult_comm; auto. rewrite minus_Sn_m; auto. destruct H0 as [k [H1 H2]]. replace 1 with (1+0) at 5; auto. rewrite H1. rewrite plus_comm. rewrite mult_comm. contradict H2. apply ModEq_minus in H2. apply ModEq_sym in H2. apply Divide_div with (pow 2 (e-1)); auto. replace (pow 2 (e-1)*2) with (pow 2 e); auto. replace e with (S(e-1)) at 1. rewrite powS; auto. destruct e. inversion H. simpl. rewrite <- minus_n_O; auto. subst e. simpl. intros C. destruct (ModEq_multN_lt C); auto. destruct x. inversion e. absurd (8<=3); auto. apply lt_not_le. apply le_S. auto. rewrite e at 2. simpl. repeat apply le_n_S. auto.
  destruct (modOrder Hc) as [o H0]. replace (pow 2 (e-2)) with o; auto. destruct (ModOrder_Divide (pow 2 (e-2)) H0). assert (Divide o (pow 2 (e-2))); auto. apply pow_Prime_Divide in H3; auto. destruct H3 as [m [H4 H5]]. apply le_lt_or_eq in H5. destruct H5; [|subst m]; auto. assert (m<=e-3). apply le_S_n. rewrite minus_Sn_m; auto. destruct (ModOrder_Divide (pow 2 (e-3)) H0). contradict Hd. apply H6. apply pow_Prime_Divide; auto. exists m; auto. Qed.
Theorem Carmichael_pow: forall p e, Prime p -> 3<=p -> e<>0 -> Carmichael (pow p e) ((p-1)*pow p (e-1)). Proof. intros. destruct (Prime_pow_ModRoot e H) as [a H2]; auto. apply Carmichael_intro with a. intros. apply Euler; auto. inversion H2. subst n g. replace ((p-1)*pow p (e-1)) with t; auto. apply Totient_unique with (pow p e); auto. Qed.
Theorem Carmichael_mult: forall n m a b c, Coprime n m -> Carmichael n a -> Carmichael m b -> LCM c a b -> Carmichael (n*m) c. Proof. intros. inversion H0. subst n0 c0. inversion H1. subst n0 c0. clear H0 H1. destruct (Chinese H a0 a1) as [d [H7 H8] _]. inversion H2. subst n0. destruct H0. destruct H9. apply Carmichael_intro with d. intros. apply Coprime_sym in H11. apply Coprime_mult_rev in H11. destruct H11. apply ModEq_Coprime_mult; auto. destruct (Divide_multN H9) as [q H13]. subst c. rewrite pow_mult. replace 1 with (pow 1 q); auto. destruct (Divide_multN H10) as [q H13]. subst c. rewrite pow_mult. replace 1 with (pow 1 q); auto.
  assert (Coprime (n*m) d). apply Coprime_sym. apply Coprime_mult; apply GCD_sym. apply GCD_ModEq with a0; auto. inversion H4; auto. apply GCD_ModEq with a1; auto. inversion H6; auto. destruct (modOrder H11) as [o H12]. replace c with o; auto. apply le_antisym. apply Divide_le; auto. destruct (ModOrder_Divide c H12). apply H14. apply ModEq_Coprime_mult; auto. apply ModOrder_Divide with a; auto. apply ModOrder_ModEq with a0; auto. apply ModOrder_Divide with b; auto. apply ModOrder_ModEq with a1; auto. apply H1. split. apply ModOrder_nz in H12; auto. inversion H12. subst a2 k. inversion H14. subst n0. destruct H15. split. rewrite mult_comm in H17. apply ModEq_mult_rev in H17. destruct (ModOrder_Divide o H4). apply H19. apply ModEq_trans with (pow d o); auto. apply ModEq_mult_rev in H17. destruct (ModOrder_Divide o H6). apply H19. apply ModEq_trans with (pow d o); auto. Qed.
Theorem Carmichael_optimum: forall n c a, Carmichael n c -> a<>0 -> (forall b, Coprime n b -> ModEq n (pow b a) 1) -> c<=a. Proof. intros. inversion H. subst n0 c0. inversion H3. subst a1 k. inversion H5. subst n0. auto. Qed.
Hint Resolve Carmichael_nz Carmichael_Min Carmichael_unique Carmichael_mult Carmichael_0 Carmichael_1 Carmichael_2 Carmichael_4 Carmichael_pow2 Carmichael_pow Carmichael_optimum.

Definition carmichael_Prime_sig: forall p e, Prime p ->{c|Carmichael (pow p e) c}. intros. destruct (nat_eq_dec e 0) as [He|He]. subst e. simpl. exists 1; auto. destruct (le_lt_dec p 2) as [Hp|Hp]. assert (p=2). apply le_antisym; auto. subst p. destruct (le_lt_dec e 2) as [Hf|Hf]. destruct e. contradict He; auto. destruct e. exists 1; auto. destruct e. exists 2; auto. contradict Hf. apply lt_not_le; auto. exists (pow 2 (e-2)); auto. exists ((p-1)*pow p (e-1)); auto. Defined.

Definition carmichael_sig: forall n, {c|Carmichael n c}. apply (Fix lt_wf). intros n IH. destruct (le_lt_dec 2 n) as [H|H]. destruct (primeDivide n) as [[p H0 H1]|H0]; [|contradict H; auto]. destruct powDivide with (a:=p) (n:=n) as [[e [y H2 H3]]|H2]; [|subst n|contradict H; subst n]; auto. destruct (nat_eq_dec e 0) as [He|He]. subst e. rewrite pow0 in H1. rewrite mult_1_l in H1; contradiction. destruct (carmichael_Prime_sig e H0) as [c1 H4]; auto. destruct (IH y) as [c2 H5]. apply lt_le_trans with (2*y). destruct y. contradict H. rewrite mult_0_r; auto. simpl. apply le_n_S. rewrite <- plus_n_Sm; auto. apply mult_le_compat_r. apply le_trans with p; auto. destruct (lcm_sig c1 c2) as [[c H6]|H6]. exists c. apply Carmichael_mult with c1 c2; auto. destruct (Prime_pow_Coprime_Divide y e H0); auto; contradiction. exfalso. destruct H6. apply Carmichael_nz in H4; contradiction. apply Carmichael_nz in H5; contradiction.
  destruct n. exists 1; auto. destruct n. exists 1; auto. contradict H; auto. Defined.
Definition carmichael (n:nat): nat := match carmichael_sig n with |exist _ c _=>c end.
